version: "3.3"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mainnet

  pgadmin:
    image: dpage/pgadmin4:6.15
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: orexkashtan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mainnet

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    networks:
      - mainnet

  app:
    build: ./app
    restart: always
    depends_on:
      - postgres
      - nginx
    networks:
      - mainnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

networks:
  mainnet:
    driver: bridge

volumes:
  postgres:
  pgadmin: